### PR TITLE
fix(tx-builder): tx-builder design adjustments 

### LINKED ISSUE #368: [TX-Builder] Design improvements
## Overview
After Lila review we have some suggestions to improve TX-Builder designs

## Goals
Add design corrections suggested by Lila

## Requirements

- [x] 1. check the distances between text fields, it should be 24px for the error text to not mess up the structure
- [x] 2. tool tip shouldn't contain a grey border, also if we can make tool tip visible only 1-2 seconds after hovering on it, so it wouldn't be as pushy for the users who already understand the interface
- [x] 3. color for hover state on a transaction (for the drag and drop action) would be #EFFAF8
- [x] 4. at the review page at the state of open transaction please follow [the design](https://www.figma.com/file/G7snLqBXWNPANcOj5MhiR7/Transaction-Builder?node-id=832%3A9776) (no grey background)

## Screens
1. Screenshot for first requirement:
Screenshot 2022-03-09 at 15 17 13

2. Screenshot for second requirement:
Screenshot 2022-03-09 at 15 21 59

3. Screenshot for third requirement:
Screenshot 2022-03-09 at 15 24 45

4. Screenshot for fourth requirement:
Screenshot 2022-03-09 at 15 28 47

### PR DESCRIPTION
**Pull request by DaniSomoza**
## What it solves
Resolves #368

## How this PR fixes it

minor fixes in the css (fields, tooltip & transaction item)

## How to test it

1. Hover a button with a tooltip and verify that no border is present.
2. In the transaction form, verify that the distance between fields is ~~24px~~ updated to 26px.
3. In the transaction list, hover and drag & drop background color should follow [the design](https://www.figma.com/file/G7snLqBXWNPANcOj5MhiR7/Transaction-Builder?node-id=832%3A9776) (no grey background)

## Screenshots

Captura de pantalla 2022-03-14 a las 16 24 18
Captura de pantalla 2022-03-14 a las 16 24 50
Captura de pantalla 2022-03-14 a las 13 44 05
Captura de pantalla 2022-03-14 a las 13 45 02
Captura de pantalla 2022-03-14 a las 13 45 30

### CODE REVIEW

File: apps/drain-safe/src/components/AddressInput.tsx [hunk 1]
```diff
@@ -4,7 +4,6 @@ import { AddressInput } from '@gnosis.pm/safe-react-components';
 export default styled(AddressInput)`
   && {
     width: 520px;
-    margin-bottom: 10px;
```
Comment (dasanra) [inline apps/drain-safe/src/components/AddressInput.tsx:7]: This was on a different app. Is this correct?

**Review by dasanra — APPROVED** [review]

**Review by mikheevm — APPROVED** [review]
