### PR TITLE
[TX Builder] Added react-hook-form to handle forms

### LINKED ISSUE #238: [TX Builder] Add minimum validation based on input type
## Overview
Currently we are not applying an exhaustive type check in the inputs, which can lead to some errors when we already know that some values are not compatible with the inputs. It also prevents us from showing a proper error to the user in the correct input field

## Goals
We should provide some basic validation at least when a field is required or it needs an explicit input type. Else we should show an error that give hints for the user if the value could be wrong

## Extra info
Here you can find a guide of types in Solidity
https://docs.soliditylang.org/en/v0.8.10/types.html#value-types

### PR DESCRIPTION
**Pull request by DaniSomoza**
## What it solves
Resolves #238

## How this PR fixes it

We added [`react-hook-form`](https://react-hook-form.com/) to handle form state and validations.

We removed de [`Builder.tsx`](https://github.com/gnosis/safe-react-apps/pull/310/files#diff-16e5843f84a6e1b9db9232230df37ba17898969b8f316153ba26767187885567) component that handled the form state and errors using [React State](https://reactjs.org/docs/hooks-state.html).

To reduce code complexity and a lot of side effects in the form state and errors we create a new set of reusable components to easily create new forms (see [the new TX-Builder designs](https://www.figma.com/proto/G7snLqBXWNPANcOj5MhiR7/Transaction-Builder?page-id=1%3A2&node-id=55%3A17805&viewport=241%2C48%2C0.18&scaling=min-zoom&starting-point-node-id=55%3A16961) like [the new Update Transaction](https://www.figma.com/proto/G7snLqBXWNPANcOj5MhiR7/Transaction-Builder?page-id=1%3A2&node-id=109%3A5609&viewport=241%2C48%2C0.18&scaling=min-zoom&starting-point-node-id=55%3A16961) modal)

New Components:

- [`AddNewTransactionForm`](https://github.com/gnosis/safe-react-apps/pull/310/files#diff-1d8b6836108a9e277a5f0b306e8e8a202d66c1410136c7955d3eeb325a71ab2b): component with the implementation of the Form that allows you to create a new Transaction.
- [`SolidityForm`](https://github.com/gnosis/safe-react-apps/pull/310/files#diff-599c064c512140d431459828e4bd98145c0e500af4ea66622204e3f2e325cbb1): Reusable component to easily create a form with all solidity fields
- [`Field.tsx`](https://github.com/gnosis/safe-react-apps/pull/310/files#diff-09565c6fb700bd6bd27224ce1638abc0777340fa3e1263b6e8514dc37a00d65c): As we are using Controlled components, we need to use [the Controller](https://react-hook-form.com/api/usecontroller/controller#main) component [see react-hook-form docs](https://react-hook-form.com/api/usecontroller/controller#main) for more details.
- Other form field Components: `AddressContractField.tsx`, `SelectContractField.tsx`, `TextContractField.tsx`, `TextareaContractField.tsx`...
- Validations: `basicSolidityValidation.ts`, `validateAddressField.ts`, `validateBooleanField.ts` ...

Yo can add custom validations to a field type in `validateField.ts` file:
```
const CUSTOM_VALIDATIONS: CustomValidationsType = {
  [ADDRESS_FIELD_TYPE]: [validateAddressField],
  [AMOUNT_FIELD_TYPE]: [validateAmountField, uintBasicValidation],
  ...
  [YOUR_FIELD_TYPE]: [isEven, lessThan30, moreThan10...],
};
```

### Transfer ether Tx

1. We Enter a EOA address in the first address input (like `rin:0x680cde08860141F9D223cE4E620B10Cd6741037E`)
2. To Address field should be auto-filled with the EOA used in the previous step.
3. ETH Value field is required (validation should be trigged if user clicks on "Add Transaction" Button).
4. If a valid EOA address and  a valid ETH amount is provided, the transaction should be added to the transaction list if user clicks on "Add Transaction" Button:
Captura de pantalla 2022-02-03 a las 18 14 22

### Data Hex Encoded Field

Use custom data (hex encoded)

1. User can send custom Hex data to a valid address using the Use custom data switch button
2. If a non hex value is provided an error should be present in the textarea field.
3.  If a valid hex value is provided the transaction should be added to the transaction list:
Captura de pantalla 2022-02-03 a las 18 20 16

### Smart contract Interaction using an address:

1. We Enter a Contract address in the first address input: `0x49d4450977E2c95362C13D3a31a09311E0Ea26A6`
2. Select a Method in the selector (`testAddress` method)
3. fill `paramAddress` (address field) with a valid address `0x680cde08860141F9D223cE4E620B10Cd6741037E`
4. Click on "Add Transactions.
Captura de pantalla 2022-02-04 a las 11 03 19

### Smart contract Interaction using ABI:
You can use this ABI:
```
[{"inputs":[{"internalType":"address","name":"paramAddress","type":"address"}],"name":"testAddress","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address[]","name":"paramArrayAddress","type":"address[]"}],"name":"testArrayAddress","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"bool[]","name":"paramArrayBool","type":"bool[]"}],"name":"testArrayBool","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"bytes[]","name":"paramArrayBytes","type":"bytes[]"}],"name":"testArrayBytes","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"bytes[]","name":"paramArrayBytes32","type":"bytes[]"}],"name":"testArrayBytes32","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256[]","name":"paramArrayInteger","type":"uint256[]"}],"name":"testArrayInteger","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256[]","name":"","type":"uint256[]"}],"name":"testArrayNoName","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"bool","name":"paramBool","type":"bool"}],"name":"testBool","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"bool","name":"","type":"bool"}],"name":"testBoolNoName","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"bytes","name":"paramBytes","type":"bytes"}],"name":"testBytes","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"bytes32","name":"paramBytes16","type":"bytes32"}],"name":"testBytes16","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"bytes32","name":"paramBytes32","type":"bytes32"}],"name":"testBytes32","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"paramInteger","type":"uint256"}],"name":"testInteger","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint8","name":"paramInteger16","type":"uint8"}],"name":"testInteger16","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint8","name":"paramInteger16","type":"uint8"}],"name":"testInteger8","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"paramLongName_abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789","type":"uint256"}],"name":"testIntegerLongParameterName","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"testIntegerNoName","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"p1","type":"uint256"},{"internalType":"bool","name":"p2","type":"bool"},{"internalType":"bytes32","name":"p3","type":"bytes32"},{"internalType":"address","name":"p4","type":"address"},{"internalType":"bool[][]","name":"p5","type":"bool[][]"},{"internalType":"bytes32[]","name":"p6","type":"bytes32[]"},{"internalType":"address[]","name":"p7","type":"address[]"}],"name":"testManyParams","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"p1","type":"uint256"},{"internalType":"bool","name":"","type":"bool"},{"internalType":"bytes32","name":"","type":"bytes32"},{"internalType":"address","name":"p4","type":"address"},{"internalType":"uint256[]","name":"","type":"uint256[]"},{"internalType":"bool[][]","name":"","type":"bool[][]"},{"internalType":"bytes32[]","name":"p7","type":"bytes32[]"},{"internalType":"address[]","name":"p8","type":"address[]"}],"name":"testManyParamsMix","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"","type":"uint256"},{"internalType":"bool","name":"","type":"bool"},{"internalType":"bytes32","name":"","type":"bytes32"},{"internalType":"address","name":"","type":"address"},{"internalType":"uint256[]","name":"","type":"uint256[]"},{"internalType":"bool[][]","name":"","type":"bool[][]"},{"internalType":"bytes32[]","name":"","type":"bytes32[]"},{"internalType":"address[]","name":"","type":"address[]"}],"name":"testManyParamsNoName","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"bool[][][][]","name":"paramNestedArrayBool","type":"bool[][][][]"}],"name":"testNestedArrayBool4Levels","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256[][]","name":"paramNestedArrayInteger","type":"uint256[][]"}],"name":"testNestedArrayInteger","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"bool[][][][][][][][][][]","name":"paramNestedArrayBool","type":"bool[][][][][][][][][][]"}],"name":"testNestedArrayInteger10Levels","outputs":[],"stateMutability":"nonpayable","type":"function"}]
```
1. We Enter the ABI in the first input:
2. Fill a ToAddress input: `0x680cde08860141F9D223cE4E620B10Cd6741037E`
3. Select a Method in the selector (`testAddress` method)
4. fill `paramAddress` (address field) with a valid address `0x680cde08860141F9D223cE4E620B10Cd6741037E`
5. Click on "Add Transactions.
Captura de pantalla 2022-02-04 a las 11 18 19

## Screenshots

Errors in the form:

Captura de pantalla 2022-02-03 a las 18 21 10
Captura de pantalla 2022-02-03 a las 18 21 42
Captura de pantalla 2022-02-03 a las 18 22 07
Captura de pantalla 2022-02-04 a las 11 06 17

### CODE REVIEW

File: apps/tx-builder/src/components/forms/SolidityForm.tsx [hunk 1]
```diff
@@ -0,0 +1,202 @@
...
+  function submitAndResetForm(values: SolodityFormValues) {
+    onSubmit(values);
+    reset(initialValues);
+    setTimeout(clearErrors, 0);
+  }
+
+  return (
+    <form id={id} onSubmit={handleSubmit(submitAndResetForm)} noValidate>
+      {/* To Address field */}
+      <Field
```
Comment (iamacook) [inline apps/tx-builder/src/components/forms/SolidityForm.tsx:62]: A lot of these props are used across multiple fields, e.g. `fullWidth`. Maybe you could export them into a reuseable component?

File: apps/tx-builder/src/components/forms/fields/AddressContractField.tsx [hunk 2]
```diff
@@ -0,0 +1,50 @@
+import styled from 'styled-components';
+import { ReactElement } from 'react';
+import { AddressInput } from '@gnosis.pm/safe-react-components';
+
+function AddressContractField({
+  id,
```
Comment (iamacook) [inline apps/tx-builder/src/components/forms/fields/AddressContractField.tsx:6]: You could spread a lot of these directly onto the component and not destructure them. It's not necessary but saves you a lot of hassle.

File: apps/tx-builder/src/components/forms/fields/Field.tsx [hunk 3]
```diff
@@ -0,0 +1,103 @@
...
+          rules={{
+            required: {
+              value: true,
+              message: 'Required',
+            },
+            validate: validateField(fieldType),
+          }}
+          render={({ field, fieldState }) => (
+            <Component
+              name={field.name}
```
Comment (iamacook) [inline apps/tx-builder/src/components/forms/fields/Field.tsx:39]: Here's another example where you could just spread `{...field}`.

File: apps/tx-builder/src/components/forms/fields/Field.tsx [hunk 4]
```diff
@@ -0,0 +1,103 @@
...
+      {showField && (
+        // see https://react-hook-form.com/advanced-usage#ControlledmixedwithUncontrolledComponents
+        <Controller
+          name={name}
+          control={control}
+          defaultValue={CUSTOM_DEFAULT_VALUES[fieldType] || ''}
+          shouldUnregister={shouldUnregister}
+          rules={{
+            required: {
+              value: true,
```
Comment (iamacook) [inline apps/tx-builder/src/components/forms/fields/Field.tsx:32]: Maybe it's best to take this from a prop so that it isn't always required? You can default it to true when you destructure it from the props though.

File: apps/tx-builder/src/utils.ts [hunk 5]
```diff
@@ -102,3 +90,47 @@ export const isValidAddress = (address: string | null) => {
...
+  if (isValidContractMethod) {
+    try {
+      const parsedValues = contractFields.map((contractField: ContractInput, index) => {
+        const contractFieldName = contractField.name || index;
+        const cleanValue = contractFieldsValues[contractFieldName] || '';
+
+        return parseInputValue(contractField, cleanValue);
+      });
+      const abi = abiCoder as unknown; // a bug in the web3-eth-abi types
+      const hexEncondedData = (abi as AbiCoder).encodeFunctionCall(contractMethod as AbiItem, parsedValues);
```
Comment (iamacook) [inline apps/tx-builder/src/utils.ts:111]: Is it safe to cast these?

File: apps/tx-builder/package.json [hunk 6]
```diff
@@ -8,6 +8,7 @@
     "@material-ui/core": "^4.12.3",
     "axios": "^0.24.0",
     "lodash": "^4.17.21",
+    "react-hook-form": "^7.25.3",
```
Comment (iamacook) [inline apps/tx-builder/package.json:11]: There are [developer tools](https://react-hook-form.com/dev-tools) that you could install as a developer dependancy (rendering them only when you're in the developer env).

File: apps/tx-builder/src/components/forms/SolidityForm.tsx [hunk 7]
```diff
@@ -0,0 +1,202 @@
...
+}: SolidityFormPropsTypes) {
+  const [showExamples, setShowExamples] = useState<boolean>(false);
+  const [showHexEncodedData, setShowHexEncodedData] = useState<boolean>(false);
+
+  const { handleSubmit, control, setValue, watch, getValues, reset, clearErrors } = useForm<SolodityFormValues>({
+    defaultValues: initialValues,
+    mode: 'onTouched', // This option allows you to configure the validation strategy before the user submits the form
+  });
+
+  const contractMethodIndex = watch(CONTRACT_METHOD_INDEX_FIELD_NAME);
```
Comment (iamacook) [inline apps/tx-builder/src/components/forms/SolidityForm.tsx:35]: If you use [`useWatch`](https://react-hook-form.com/api/usewatch), it will isolate re-renders.

**Review by iamacook — COMMENTED** [review]
Looks way cleaner! 🚀

File: apps/tx-builder/src/components/forms/SolidityForm.tsx [hunk 8]
```diff
@@ -0,0 +1,202 @@
...
+  networkPrefix,
+  contract,
+  children,
+}: SolidityFormPropsTypes) {
+  const [showExamples, setShowExamples] = useState<boolean>(false);
+  const [showHexEncodedData, setShowHexEncodedData] = useState<boolean>(false);
+
+  const { handleSubmit, control, setValue, watch, getValues, reset, clearErrors } = useForm<SolodityFormValues>({
+    defaultValues: initialValues,
+    mode: 'onTouched', // This option allows you to configure the validation strategy before the user submits the form
```
[the remark this answers is not in the document]
Comment (DaniSomoza) [reply apps/tx-builder/src/components/forms/SolidityForm.tsx:32]: Good catch!
From [the docs](https://react-hook-form.com/api/useform#main):

- mode: `all`:  Validation will trigger on the blur and change events.
- mode: `onTouched`:  Validation will trigger on the first blur event. After that, it will trigger on every change event.

Basically, I used `onTouched` mode because when you start typing, the error doesn't show until you blur the field for first time (after this, validation is triggered on every change field event)

But I will update this to mode: `all` because its the current behaviour in the tx-builder.

[the remark this answers is not in the document]
Comment (iamacook) [reply apps/tx-builder/src/components/forms/SolidityForm.tsx:32]: It's up to you. The comment seemed as though it was copied from an example.

File: apps/tx-builder/src/components/forms/SolidityForm.tsx (hunk 7 above)
Comment (DaniSomoza) [reply apps/tx-builder/src/components/forms/SolidityForm.tsx:35]: mmm, I think that in this case we should use `watch()` right?

I think that [useWatch](https://react-hook-form.com/api/usewatch) its meant to be used in a nested component. useWatch will isolate re-render only that component and potentially result in better performance.

Also that component needs to be wrapped with a [FormProvider](https://react-hook-form.com/advanced-usage#FormProviderPerformance), it uses a [React's Context](https://reactjs.org/docs/context.html) API. 
It think that it only makes sense if the data is passed through a very complex components tree. In that case it saves you to having to pass props down manually at every level.

What is your opinion about that?

Comment (iamacook) [reply apps/tx-builder/src/components/forms/SolidityForm.tsx:35]: I suppose as you're using it within this component then it may not be necessary.

It requires `control`, which is likely the explanation for the context.

File: apps/tx-builder/src/components/forms/SolidityForm.tsx [hunk 9]
```diff
@@ -0,0 +1,202 @@
...
+      <Field
+        id="to-address-input"
+        name={TO_ADDRESS_FIELD_NAME}
+        label="To Address"
+        fullWidth
+        required
+        getAddressFromDomain={getAddressFromDomain}
+        networkPrefix={networkPrefix}
+        fieldType={ADDRESS_FIELD_TYPE}
+        control={control}
```
[the remark this answers is not in the document]
Comment (DaniSomoza) [reply apps/tx-builder/src/components/forms/SolidityForm.tsx:71]: As I mention in [this other comment](https://github.com/gnosis/safe-react-apps/pull/310/files#r798587579). I think that [FormProvider](https://react-hook-form.com/advanced-usage#FormProviderPerformance) only makes sense if the data is passed through a very complex components tree. In that case it saves you to having to pass props down manually at every level. 

But I think that it is not our case right?

File: apps/tx-builder/src/components/forms/SolidityForm.tsx (hunk 8 above)
[the remark this answers is not in the document]
Comment (yagopv) [reply apps/tx-builder/src/components/forms/SolidityForm.tsx:32]: For me personally onTouched leads to a better UX @DaniSomoza

File: apps/tx-builder/src/components/forms/SolidityForm.tsx [hunk 10]
```diff
@@ -0,0 +1,202 @@
...
+
+      {/* Native Token Amount Input */}
+      <Field
+        id="token-value-input"
+        name={TOKEN_INPUT_NAME}
+        label={`${nativeCurrencySymbol} value`}
+        fieldType={AMOUNT_FIELD_TYPE}
+        fullWidth
+        required
+        showField={isValueInputVisible}
```
[the remark this answers is not in the document]
Comment (DaniSomoza) [reply apps/tx-builder/src/components/forms/SolidityForm.tsx:83]: Yes, I am using 2 props for this (I need to finish my PR description to specify this sorry :< )

- prop `showField`: This allows you to visually show/hide the component field
- prop `shouldUnregister`: This allows you to keep/remove the field value in the form state when you visually show/hide the component field. (we need this when we switch between encoding/decoding contract fields values to hex data)

File: apps/tx-builder/src/components/forms/SolidityForm.tsx (hunk 9 above)
[the remark this answers is not in the document]
Comment (yagopv) [reply apps/tx-builder/src/components/forms/SolidityForm.tsx:71]: If you add a Context API provider you lose the nice of the uncontrolled components don't you?

File: apps/tx-builder/src/components/forms/SolidityForm.tsx (hunk 10 above)
[the remark this answers is not in the document]
Comment (iamacook) [reply apps/tx-builder/src/components/forms/SolidityForm.tsx:83]: I think `showField` shoul be outside of the component, no? `flag && <Field {...props />`

You can enable `shouldUnregister` by default in `userForm` if it helps. Just a suggestion ;)

File: apps/tx-builder/src/components/forms/SolidityForm.tsx (hunk 9 above)
[the remark this answers is not in the document]
Comment (iamacook) [reply apps/tx-builder/src/components/forms/SolidityForm.tsx:71]: RHF provides hooks to interact with the `FormProvider` context and reduce associated re-renders.

[the remark this answers is not in the document]
Comment (iamacook) [reply apps/tx-builder/src/components/forms/SolidityForm.tsx:71]: If we're not nesting fields then we need not use it though.

File: apps/tx-builder/src/components/forms/SolidityForm.tsx [hunk 11]
```diff
@@ -0,0 +1,202 @@
...
+      {/* Contract Section */}
+
+      {/* Contract Method Selector */}
+      <Field
+        id="contract-method-selector"
+        name={CONTRACT_METHOD_INDEX_FIELD_NAME}
+        label={'Contract Method Selector'}
+        fieldType={CONTRACT_METHOD_FIELD_TYPE}
+        showField={showContractFields}
+        shouldUnregister={false}
```
[the remark this answers is not in the document]
Comment (iamacook) [reply apps/tx-builder/src/components/forms/SolidityForm.tsx:127]: Seems like the `useForm` argument overwrite child-level setting, so I'll resolve this.

File: apps/tx-builder/src/components/forms/SolidityForm.tsx (hunk 8 above)
[the remark this answers is not in the document]
Comment (DaniSomoza) [reply apps/tx-builder/src/components/forms/SolidityForm.tsx:62]: restored mode to `onTouched`

File: apps/tx-builder/src/components/forms/SolidityForm.tsx (hunk 10 above)
[the remark this answers is not in the document]
Comment (DaniSomoza) [reply apps/tx-builder/src/components/forms/SolidityForm.tsx:113]: I added a `showField` prop to perform the conditional rendering inside of the `Field` Component:
 
And regarding `shouldUnregister`, based [on the v7 docs](https://react-hook-form.com/api/useform): 
By default, an input value will be retained in the form state when input is removed. You can set `shouldUnregister` to `true` to unregister input during unmount in the `useForm`, but the problem is:
```
This is a global config that overwrites child-level config, if you want to have individual behavior, then you should set the config at the component or hook level, not at useForm.
```
In some cases we want to keep some values in the form state. Based on the docs the only way to do this properly is using directly the child-level config (using the `shouldUnregister` prop)

File: apps/tx-builder/src/components/forms/SolidityForm.tsx [hunk 12]
```diff
@@ -0,0 +1,202 @@
...
+        showErrorsInTheLabel={false}
+      />
+
+      {/* Contract Section */}
+
+      {/* Contract Method Selector */}
+      <Field
+        id="contract-method-selector"
+        name={CONTRACT_METHOD_INDEX_FIELD_NAME}
+        label={'Contract Method Selector'}
```
[the remark this answers is not in the document]
Comment (DaniSomoza) [reply apps/tx-builder/src/components/forms/SolidityForm.tsx]: done!

File: apps/tx-builder/src/components/forms/SolidityForm.tsx [hunk 13]
```diff
@@ -0,0 +1,202 @@
...
+        return (
+          <Field
+            key={name}
+            id={`contract-field-${contractField.name || index}`}
+            name={name}
+            label={`${contractField.name || `${index + 1}º contract field`} (${contractField.type})`}
+            fieldType={contractField.type}
+            fullWidth
+            required
+            shouldUnregister={false} // required to keep contract field values in the form state when the user switches between encoding and decoding data
```
[the remark this answers is not in the document]
Comment (DaniSomoza) [reply apps/tx-builder/src/components/forms/SolidityForm.tsx:159]: see [this comment](https://github.com/gnosis/safe-react-apps/pull/310#discussion_r800792700)

File: apps/tx-builder/src/components/forms/fields/Field.tsx (hunk 4 above)
Comment (DaniSomoza) [reply apps/tx-builder/src/components/forms/fields/Field.tsx]: Good Catch! All fields are required now, but as you mention it's best to take this from a prop, because in the future we could need it:
```
          rules={{
            required: {
              value: required,
              message: 'Required',
            },
            valida
```

File: apps/tx-builder/src/utils.ts (hunk 5 above)
Comment (DaniSomoza) [reply apps/tx-builder/src/utils.ts:111]: yep it seems that its a bug related with the `web3-eth-abi` lib.

File: apps/tx-builder/package.json (hunk 6 above)
Comment (DaniSomoza) [reply apps/tx-builder/package.json:11]: done! :D

File: apps/tx-builder/src/components/forms/SolidityForm.tsx [hunk 14]
```diff
@@ -0,0 +1,208 @@
...
+          <Switch checked={showHexEncodedData} onChange={onClickShowHexEncodedData} />
+          Use custom data (hex encoded)
+        </Text>
+
+        {/* action buttons as a children */}
+        {children}
+      </form>
+
+      {/* set up the dev tool */}
+      <DevTool control={control} />
```
[the remark this answers is not in the document]
Comment (DaniSomoza) [reply apps/tx-builder/src/components/forms/SolidityForm.tsx]: done!

File: apps/tx-builder/src/components/forms/SolidityForm.tsx (hunk 10 above)
[the remark this answers is not in the document]
Comment (DaniSomoza) [reply apps/tx-builder/src/components/forms/SolidityForm.tsx]: No reason behind that, I removed the `showField`  prop from `Field` component.

now, if you want to show/hide a form field you shoould use conditional rendering from outside:

```
        {showContractFields && (
          <Field
            id="contract-method-selector"
            [...]
```

**Review by iamacook — APPROVED** [review]
Great work dude! 💪

File: apps/tx-builder/src/components/forms/validations/validateAmountField.ts [hunk 15]
```diff
@@ -0,0 +1,11 @@
+import { ValidateResult } from 'react-hook-form';
+
+import { isInputValueValid } from '../../../utils';
```
Comment (dasanra) [inline apps/tx-builder/src/components/forms/validations/validateAmountField.ts:3]: Not to be done in this PR, but is better if we use the same approach of absolute routes if possible, we should check it

**Comment by JagoFigueroa** [comment]
For now only issue I've found is that when working with assets, no decimals are allowed. @DaniSomoza is already doing his magic to fix it

Screenshot 2022-02-14 at 16 26 23

Cheers!

**Comment by DaniSomoza** [comment]
@JagoFigueroa  Good Catch! 

Fixed! :D

I added this validation to the `validateAmountField.ts` fn:

```
  // should be a valid amount in wei
  try {
    toWei(value);
  } catch (error) {
    return INVALID_AMOUNT_ERROR;
  }
```

I added a unit test to make sure that we show errors for invalid decimal amounts:

```
      it('validates invalid decimal amounts', () => {
        const validationResult = validateAmountField('0.000000000000000000000000000000001');

        expect(validationResult).toBe('Invalid amount value');
      });
```

File: apps/tx-builder/src/components/forms/AddNewTransactionForm.tsx [hunk 16]
```diff
@@ -0,0 +1,137 @@
...
+}: AddNewTransactionFormProps) => {
+  const [showReviewModal, setShowReviewModal] = useState(false);
+  const showABIWarning = contract && !contract?.methods.length;
+
+  const initialFormValues = {
+    [TO_ADDRESS_FIELD_NAME]: isValidAddress(to) ? to : '',
+    [CONTRACT_METHOD_INDEX_FIELD_NAME]: '0',
+  };
+
+  function onSubmit(values: SolidityFormValuesTypes) {
```
Comment (mikheevm) [inline apps/tx-builder/src/components/forms/AddNewTransactionForm.tsx:50]: this function is defined with `function` keyword but the component is defined with an arrow function, let's stay consistent

File: apps/tx-builder/src/components/forms/SolidityForm.tsx [hunk 17]
```diff
@@ -0,0 +1,214 @@
...
+
+  const contractMethodIndex = watch(CONTRACT_METHOD_INDEX_FIELD_NAME);
+  const contractMethod = contract?.methods[Number(contractMethodIndex)];
+  const contractFields = contractMethod?.inputs || [];
+  const showContractFields = !!contract && !showHexEncodedData;
+  const isPayableMethod = !!contract && contractMethod?.payable;
+
+  const isValueInputVisible = showHexEncodedData || !contract || isPayableMethod;
+
+  function onClickShowHexEncodedData(checked: boolean) {
```
Comment (mikheevm) [inline apps/tx-builder/src/components/forms/SolidityForm.tsx:76]: same here with the definitions

File: apps/tx-builder/src/components/forms/fields/TextareaContractField.tsx [hunk 18]
```diff
@@ -0,0 +1,10 @@
+import { TextFieldInputProps } from '@gnosis.pm/safe-react-components/dist/inputs/TextFieldInput';
+import TextContractField from './TextContractField';
+
+const DEFAULT_ROWS = 4;
+
+const TextareaContractField = (props: TextFieldInputProps) => {
+  return <TextContractField {...props} multiline rows={DEFAULT_ROWS} />;
```
Comment (mikheevm) [inline apps/tx-builder/src/components/forms/fields/TextareaContractField.tsx:7]: should rows be editable?

Comment (DaniSomoza) [reply apps/tx-builder/src/components/forms/fields/TextareaContractField.tsx:7]: Good point! 

Now `rows` are editable:

```
<TextContractField {...props} multiline rows={props.rows || DEFAULT_ROWS} />;
```

File: apps/tx-builder/src/components/forms/SolidityForm.tsx (hunk 17 above)
Comment (DaniSomoza) [reply apps/tx-builder/src/components/forms/SolidityForm.tsx]: done!

File: apps/tx-builder/src/components/forms/AddNewTransactionForm.tsx (hunk 16 above)
Comment (DaniSomoza) [reply apps/tx-builder/src/components/forms/AddNewTransactionForm.tsx]: done!

**Comment by JagoFigueroa** [comment]
All bueno! Gracias @DaniSomoza :pepe-king:
