### PR TITLE
Fix balances display in Drain Safe

### LINKED ISSUE #114: Drain Account
<Placeholder ticket, spec is just a draft>

Sometimes you just want to move on... This Safe App would allow to empty all assets from your Gnosis Safe account and send them somewhere else.

- Transfer all known ETH, ERC20, ERC721, etc. belonging to a Safe to a new address in one transaction
- Could be as easy as just an input field with a recipient address and a "Drain all assets" button or could also display a list of all assets where the user could select individual asset types to drain

### PR DESCRIPTION
**Pull request by katspaugh**
Closes #114.

Fixes some of the issues found by @liliya-soroka in #120:

- [x] Decimals are not taken into account for the token value:
Drain account app :

Actual values on balance page where decimals are taken into account:

- [x] no default icon for the tokens without icon as on balance page :
Current result: __
Expected result:

### CODE REVIEW

**Comment by katspaugh** [comment]
NB: for missing icons, I'm just not displaying any image.

File: apps/drain-safe/src/components/Icon.tsx [hunk 1]
```diff
@@ -12,9 +12,11 @@ const IconImg = styled.img`
   width: auto;
 `;
 
-function Icon(props: Props): JSX.Element {
+function Icon(props: Props): JSX.Element | null {
+  const [noIcon, setNoIcon] = useState<boolean>(false);
   const { logoUri, symbol } = props;
-  return <IconImg src={logoUri} alt={symbol} />;
+
+  return noIcon ? null : <IconImg src={logoUri} alt={symbol} onError={() => setNoIcon(true)} />;
```
Comment (dasanra) [inline apps/drain-safe/src/components/Icon.tsx:19]: Would it make sense to use the 'assets' icon from safe-react-components inside a greyed circle, similar as we do in the assets tab?
https://components.gnosis-safe.io/?path=/docs/data-display-icon--icons

image

image

**Review by dasanra — COMMENTED** [review]
I can still see the arrow for sorting when hovering table titles. What do you think about removing it as is not possible to do frontend sorting?

**Comment by katspaugh** [comment]
> I can still see the arrow for sorting when hovering table titles. What do you think about removing it as is not possible to do frontend sorting?

The arrow cannot be removed as of now. I'll fix this in the SRC repo. See https://github.com/gnosis/safe-react-components/issues/128

File: apps/drain-safe/src/components/Icon.tsx (hunk 1 above)
Comment (katspaugh) [reply apps/drain-safe/src/components/Icon.tsx]: The assets icon is used in the sidebar menu so I think it might be confusing.
I've added a question mark icon as a fallback (like Uniswap).

Screenshot 2021-05-05 at 09 24 26

**Review by dasanra — APPROVED** [review]

**Comment by liliya-soroka** [comment]
Verified
nice app
