### PR TITLE
[TX BUILDER] Add input validation before adding transactions

### LINKED ISSUE #195: [Tx Builder] Don't allow to perform transactions with negative values
## Description
We should not allow to add an address to address transaction when the {{asset}} value field is negative

## Steps to reproduce
Go to Transaction Builder app and add a new address to address transaction with negative value:
 

Screenshot 2021-12-01 at 09 49 46

## Expected result
Frontend validation blocks the user of adding a negative transaction

## Obtained result
Transaction(s) can be added and executed.

### PR DESCRIPTION
**Pull request by yagopv**
## What it solves
Resolves #195 

## How this PR fixes it
Adding validation for the input value before adding the transaction

## How to test it
1) Add a contract with no abi
2) Enter incorrect values like characters, negatives ... and check you cannot add a transaction after pressing the "Add transaction" button
3) Add correct values and check you can add transactions

### CODE REVIEW

**Comment by mikheevm** [comment]
Hey, I'm not sure if you saw [my comment](https://github.com/gnosis/safe-react-apps/issues/195#issuecomment-981614117), but in short, there are certain cases where transactions with 0 value may be helpful, and it's not clear whether this is a bug. So IMO we should ask for product/team opinion.

File: apps/tx-builder/src/components/Builder.tsx [hunk 1]
```diff
@@ -143,6 +152,11 @@ export const Builder = ({
       return;
     }
 
+    if (!isInputValueValid(valueInput)) {
+      setValueError(`${nativeCurrencySymbol} value`);
+      return;
+    }
+
```
Comment (dasanra) [inline apps/tx-builder/src/components/Builder.tsx:159]: Wouldn't it make more sense to disable the button?

Shouldn't it be already showing the error value, that should be set in the function `onValueInputChange`?

Comment (yagopv) [reply apps/tx-builder/src/components/Builder.tsx:159]: I think is better to let the user make errors by pressing buttons. Disabling buttons i think is a little frustrating from a user perspective because sometimes you don't know what to do.

Besides that, If we would like to go that way perhaps we should do the same with the other form fields right? ... for keeping consistency

File: apps/tx-builder/src/components/Builder.tsx [hunk 2]
```diff
@@ -123,6 +123,15 @@ export const Builder = ({
     setInputCache(inputCache.slice());
   };
 
+  const isInputValueValid = useCallback((val: string) => {
```
Comment (mikheevm) [inline apps/tx-builder/src/components/Builder.tsx:126]: You can define this function outside the component body and you won't need `useCallback`

Comment (yagopv) [reply apps/tx-builder/src/components/Builder.tsx:126]: yes I can do it.

In this concrete component there are a lot of functions created inside and outside but there is no concrete pattern for doing it. What I'm doing in this issue #214  is extracting the functions from outside the component to the utils file. What do you think if I do the same with this?

Comment (mikheevm) [reply apps/tx-builder/src/components/Builder.tsx:126]: I think it's OK to keep functions in a single file if you don't use them in other files. No strong preference, though.

> there is no concrete pattern for doing it

well, besides the pattern, using it with useCallback is less efficient because the memoization isn't free

Comment (yagopv) [reply apps/tx-builder/src/components/Builder.tsx]: yes, with "pattern" i mean in this concrete component there are more useCallback uses that doesn't make sense for the same memoization issues you are mentioning and should be extracted as well. I will do it in the other issue i'm developing.

I extracted this function to outside anyway. Thanks !!

**Review by mikheevm — APPROVED** [review]
gracias

File: apps/tx-builder/src/components/Builder.tsx (hunk 1 above)
Comment (dasanra) [reply apps/tx-builder/src/components/Builder.tsx:159]: Not a strong opinion there, we can get over this again if necessary when we have design updates

**Review by dasanra — APPROVED** [review]

**Comment by JagoFigueroa** [comment]
Input validation is working as expected. I was talking with @yagopv and we noticed that after the component changes for the address input implemented by @DaniSomoza  and his, now we have 3 different types of styling for the fields present in this app when front validation kicks in:

Screenshot 2021-12-02 at 15 09 07

Screenshot 2021-12-02 at 15 32 03

What do you think if I create a separate improvement to have this behaviour aligned for all fields @dasanra ?

**Comment by dasanra** [comment]
@JagoFigueroa Perfect for me. We can close this ticket and work in a new one to align input validation styles

**Comment by yagopv** [comment]
background colors are different as well. Going to merge as this is in develop already
